// Auto-generated by setup.py for Hydroponic PlantHub ESP32

#ifndef CONFIG_H
#define CONFIG_H

// WiFi Configuration
#define WIFI_SSID     "YOUR_SSID"
#define WIFI_USERNAME "YOUR_USERNAME" // Only needed for secure networks
#define WIFI_PASSWORD "YOUR_PASSWORD"

// MQTT Configuration
#define MQTT_SERVER   "test.mosquitto.org"
#define MQTT_PORT     1883

// Plant Module ID
#define PLANT_MODULE_ID "bf6916df-adbb-478d-95dd-707977058ece"

// Sensor Pins
// DHT sensor for Temperature & Humidity
#define DHTPIN 13
#define DHTTYPE 22
#define TDS_PIN 34
#define FLOAT_PIN 11
#define LIGHT_ANALOG_PIN 36

// Control Pins
#define RELAY_N_PIN 25
#define RELAY_P_PIN 26
#define RELAY_K_PIN 27
#define RELAY_LIGHT_PIN 10

// NTP Config
#define NTP_SERVER          "pool.ntp.org"
#define GMT_OFFSET_SEC      0
#define DAYLIGHT_OFFSET_SEC 3600

#define MS_PER_ML_N 100  // 1 mL per 100 ms for Nitrogen
#define MS_PER_ML_P 120  // 1 mL per 120 ms for Phosphorus
#define MS_PER_ML_K 110  // 1 mL per 110 ms for Potassium

#endif
